name: reddit_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  flutter_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
  google_sign_in: 5.4.4    
  fpdart: ^1.1.1
  routemaster: ^1.0.1
  dotted_border: ^3.1.0
  file_picker: ^10.2.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  any_link_preview: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/google.png
   - assets/images/loginEmote.png
   - assets/images/logo.png
   - assets/images/awards/

  
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf