// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG4ZwF0EuEiLUymsB4KDHnZ9pOCnn783k',
    appId: '1:541699605185:web:a3be1e78df0a0ca53b8a40',
    messagingSenderId: '541699605185',
    projectId: 'reddit-clone-d5a84',
    authDomain: 'reddit-clone-d5a84.firebaseapp.com',
    storageBucket: 'reddit-clone-d5a84.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIMM-lDxe9WXYS_y3JAmKghrRsFcEJYL8',
    appId: '1:541699605185:android:df2d0f8effe86be73b8a40',
    messagingSenderId: '541699605185',
    projectId: 'reddit-clone-d5a84',
    storageBucket: 'reddit-clone-d5a84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPhNHfQrCebMAWm5k-UFcdm2h8x6LKn8s',
    appId: '1:541699605185:ios:ac32667e07fdee2a3b8a40',
    messagingSenderId: '541699605185',
    projectId: 'reddit-clone-d5a84',
    storageBucket: 'reddit-clone-d5a84.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );
}
